//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HMS_DBEntity : DbContext
    {
        public HMS_DBEntity()
            : base("name=HMS_DBEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdmissionType> tblAdmissionTypes { get; set; }
        public virtual DbSet<tblDoctor> tblDoctors { get; set; }
        public virtual DbSet<tblEmployeeType> tblEmployeeTypes { get; set; }
        public virtual DbSet<tblHospital> tblHospitals { get; set; }
        public virtual DbSet<tblHospitalRoom> tblHospitalRooms { get; set; }
        public virtual DbSet<tblMedicine> tblMedicines { get; set; }
        public virtual DbSet<tblMedicineCategory> tblMedicineCategories { get; set; }
        public virtual DbSet<tblMedicineOccurance> tblMedicineOccurances { get; set; }
        public virtual DbSet<tblMedicineTiming> tblMedicineTimings { get; set; }
        public virtual DbSet<tblPatient> tblPatients { get; set; }
        public virtual DbSet<tblPatientBill> tblPatientBills { get; set; }
        public virtual DbSet<tblPatientBillDetail> tblPatientBillDetails { get; set; }
        public virtual DbSet<tblPatientMedicine> tblPatientMedicines { get; set; }
        public virtual DbSet<tblPatientStatu> tblPatientStatus { get; set; }
        public virtual DbSet<tblPatientTest> tblPatientTests { get; set; }
        public virtual DbSet<tblPatientTestDetail> tblPatientTestDetails { get; set; }
        public virtual DbSet<tblPatientType> tblPatientTypes { get; set; }
        public virtual DbSet<tblRoomType> tblRoomTypes { get; set; }
        public virtual DbSet<tblTest> tblTests { get; set; }
        public virtual DbSet<tblTestAttribute> tblTestAttributes { get; set; }
        public virtual DbSet<tblTestCategory> tblTestCategories { get; set; }
        public virtual DbSet<UserInRole> UserInRoles { get; set; }
        public virtual DbSet<UserLoginHistory> UserLoginHistories { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<tblEmployeeSatu> tblEmployeeSatus { get; set; }
        public virtual DbSet<tblEmpDesignation> tblEmpDesignations { get; set; }
        public virtual DbSet<tblEmployeeQualification> tblEmployeeQualifications { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblPatientAdmission> tblPatientAdmissions { get; set; }
        public virtual DbSet<tblPatientAppointment> tblPatientAppointments { get; set; }
    
        public virtual ObjectResult<GetPatientList_Result> GetPatientList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPatientList_Result>("GetPatientList");
        }
    
        public virtual ObjectResult<GetpatientTestDetails_Result> GetpatientTestDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetpatientTestDetails_Result>("GetpatientTestDetails");
        }
    }
}
