//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        public int ID { get; set; }
        public string DoctorName { get; set; }
        public string Speciality { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> HospitalID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblHospital tblHospital { get; set; }
    }
}
