//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatientBillDetail
    {
        public int ID { get; set; }
        public Nullable<int> PatientBillID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public string Description { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual tblPatientBill tblPatientBill { get; set; }
    }
}
