//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatientMedicine
    {
        public int ID { get; set; }
        public Nullable<int> PatientAppointmentID { get; set; }
        public Nullable<int> MedicineID { get; set; }
        public string Timing { get; set; }
        public string NoofDays { get; set; }
        public string Occurance { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Description { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual tblMedicine tblMedicine { get; set; }
        public virtual tblPatientAppointment tblPatientAppointment { get; set; }
    }
}
