//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPatientTestDetail
    {
        public int ID { get; set; }
        public Nullable<int> PatientTestID { get; set; }
        public Nullable<int> TestAttributeID { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual tblPatientTest tblPatientTest { get; set; }
        public virtual tblTestAttribute tblTestAttribute { get; set; }
    }
}
