//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserRolePage
    {
        public int id { get; set; }
        public int RoleId { get; set; }
        public int PageId { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual tblPage tblPage { get; set; }
    }
}
