//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserPage
    {
        public int id { get; set; }
        public Nullable<int> page_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> Role_id { get; set; }
        public Nullable<bool> show_in_menu { get; set; }
    }
}
