//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserInRoles = new HashSet<UserInRole>();
            this.UserLoginHistories = new HashSet<UserLoginHistory>();
        }
    
        public long ID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string Email { get; set; }
        public bool IsSuperUser { get; set; }
        public bool UpdatePassword { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public int TotalLogins { get; set; }
        public Nullable<int> LoginFailedAttempts { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<System.DateTime> LastLoginOnDate_Server { get; set; }
        public string BrowserType { get; set; }
        public string PlateForm { get; set; }
        public bool IsClosed { get; set; }
        public string ClosedReason { get; set; }
        public Nullable<System.DateTime> ClosedOnDate { get; set; }
        public Nullable<long> ClosedByUserID { get; set; }
        public bool IsLockedOut { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Hospital_ID { get; set; }
    
        public virtual tblHospital tblHospital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInRole> UserInRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLoginHistory> UserLoginHistories { get; set; }
    }
}
