//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInRole
    {
        public int ID { get; set; }
        public long UserID { get; set; }
        public int UserRoleID { get; set; }
        public Nullable<System.DateTime> EffectiveFromDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual User User { get; set; }
    }
}
