//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLoginHistory
    {
        public long ID { get; set; }
        public long UserId { get; set; }
        public string PasswordUsed { get; set; }
        public System.DateTime LoginDate { get; set; }
        public string LoginIP { get; set; }
        public string BrowserType { get; set; }
        public string PlateForm { get; set; }
        public string CurrentUser { get; set; }
        public string HostName { get; set; }
        public bool IsFailedAttempt { get; set; }
    
        public virtual User User { get; set; }
    }
}
